runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: app.static
- url: /.*
  script: app.app
  
libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
- name: MySQLdb
  version: "latest"
